**Numpy Array**

Num: Numerical

Py: Python

In [37]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
np.array(['abc',2,3])

array(['abc', '2', '3'], dtype='<U3')

In [ ]:
type(np.array(['abc',2,3]))

#nparray: n dimensional array

numpy.ndarray

In [ ]:
#Upcasting:

np.array([1,2,3.0])

#Upcasting gives the floating point number here.Numpy does the upcasting operation.s

array([1., 2., 3.])

In [ ]:
#two dimensions

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[1,2],[3,4]],ndmin=6)

array([[[[[[1, 2],
           [3, 4]]]]]])

In [ ]:
np.array([1,2,3],ndmin=5)

#ndmin: number of dimensions

array([[[[[1, 2, 3]]]]])

In [ ]:
#dtype

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data -type consisting of more than one element:

x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [ ]:
type(x[1][0])

numpy.int16

In [ ]:
arr=np.array([(1,2),(3,4)])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
arr[0][1]

2

In [ ]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [ ]:
type(x[0][1])

numpy.int64

In [ ]:
x[1][1]

4

In [ ]:
type(x)

numpy.ndarray

In [ ]:
#creating an array from sub-classes

np.array([[1,2],[4,7]])

array([[1, 2],
       [4, 7]])

In [ ]:
np.mat(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [ ]:
np.mat('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.mat([1,2])

matrix([[1, 2]])

In [ ]:
np.mat([[1,2],[5,6]])

matrix([[1, 2],
        [5, 6]])

In [ ]:
np.mat([[1,2],[5,6,7]])

matrix([[list([1, 2]), list([5, 6, 7])]], dtype=object)

**numpy.asarray**

In [ ]:
#convert a list into array

In [ ]:
a=[1,2]
type(a)
np.asarray(a)

array([1, 2])

In [ ]:
a=[[1,2],[6,7]]
type(a)
np.asarray(a)

array([[1, 2],
       [6, 7]])

In [ ]:
a=np.array([1,2],dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
np.asarray([1,2]) is a

#a is floating value

False

In [ ]:
#Matrx is a subclass of array

issubclass(np.matrix,np.ndarray)

True

In [ ]:
issubclass(np.ndarray,np.matrix)

False

**numpy.asanyarray**

In [ ]:
a=[1,2]
np.asanyarray(a)

#asanyarray will convert any dataset to array.
#List is not a subclass of array. Hence np.asanyarray converted it to array.


array([1, 2])

In [ ]:
type(np.asanyarray(a))

numpy.ndarray

In [ ]:
a=np.matrix([1,2])
a

matrix([[1, 2]])

In [ ]:
np.asanyarray(a)
#matrix is a subclass of array.Hence np.asanyarray doesnt make any change.

matrix([[1, 2]])

In [ ]:
#array and asarray will convert matrix to array

np.array(a)

array([[1, 2]])

In [ ]:
np.asarray(a)

array([[1, 2]])

In [ ]:
#asanyarray wont convert matrix to array

np.asanyarray(a)

matrix([[1, 2]])

**numpy.copy**

In [ ]:
np.array(a,copy=True)

array([[1, 2]])

In [ ]:
#create an array x, with a reference y and a copy z

x=np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y=x

In [ ]:
z=np.copy(x)
z

array([1, 2, 3])

In [ ]:
y[0]=100
y

array([100,   2,   3])

In [ ]:
x

#we observe that if we change any value of y , value of x will also get changed. As y=x.

array([100,   2,   3])

In [ ]:
print(id(x))
print(id(y))

#both are pointing to same location

140072336056448
140072336056448


In [ ]:
z=np.copy(x)
z

array([100,   2,   3])

In [ ]:
z[1]=2345
z

array([ 100, 2345,    3])

In [ ]:
x

array([100,   2,   3])

**numpy.fromfunction**

In [ ]:
#construct an array by executing a function over each coordinate

np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
#3D array

np.fromfunction(lambda i,j,k: i*j*k,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [ ]:
np.fromfunction(lambda i,j,k,m: i*j*k*m,(3,3,3,3),dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [ ]:
#create a 1D array from an iterable object

iterable=(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x7f5d70258bd0>

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

a=np.fromstring('245 245',sep=' ')
a

array([245., 245.])

In [ ]:
np.fromstring('1,2',dtype=int,sep=',')

array([1, 2])

In [ ]:
#how to create a record array from a (float) list of arrays

x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [ ]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

**data types**

In [ ]:
my_list=[1,2,3]
arr=np.array(my_list)
print("Type/class of this array",type(arr))
print("Here is the vector\n-------------------\n",arr)

Type/class of this array <class 'numpy.ndarray'>
Here is the vector
-------------------
 [1 2 3]


In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print('Type/class of matrix:',type(mat))
print('Here is the matrix\n----------\n',mat,'\n----------\n')
print('Dimension of matrix:',mat.ndim,sep='')
print('Size of matrix:',mat.size,sep='')
print('Shape of matrix:',mat.shape,sep='')
print('Data type of matrix:',mat.dtype,sep='')

Type/class of matrix: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------

Dimension of matrix:2
Size of matrix:9
Shape of matrix:(3, 3)
Data type of matrix:int64


In [ ]:
my_mat=[[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat=np.array(my_mat)
print('Data type of matrix:',mat.dtype,sep='')

Data type of matrix:float64


In [ ]:
print('Even tuples can be converted into ndarray\n-------------------------------------------\n')
b=np.array([(1.1,2,3),(4,5,6)])
print(type(b))
print(b)

Even tuples can be converted into ndarray
-------------------------------------------

<class 'numpy.ndarray'>
[[1.1 2.  3. ]
 [4.  5.  6. ]]


**arange and linspace**

In [ ]:
list(range(4,7))

[4, 5, 6]

In [ ]:
list(range(4,20,2))

#we cannot use floating point number in case of range function. Range function always consider an integer data type.

[4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
#python doesn't have arange function but numpy has. hence we use np.arange()

np.arange(4,30,2.8)

array([ 4. ,  6.8,  9.6, 12.4, 15.2, 18. , 20.8, 23.6, 26.4, 29.2])

In [ ]:
np.arange(2.3,8.4,1.5)

array([2.3, 3.8, 5.3, 6.8, 8.3])

In [ ]:
np.arange(16,0,-2)

array([16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
print('A series of numbers:',type(np.arange(5,16)))
np.arange(5,16,2.3) #A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [ ]:
list(range(50,-1,5))

[]

In [ ]:
print('Numbers spaced apart by 2:',np.arange(50,-1,5))

Numbers spaced apart by 2: []


In [ ]:
print('Number spaced apart by float:',np.arange(0,11,2.5))

Number spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [ ]:
print('Every 5th number from 50 in reverse order\n',np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [ ]:
print('linearly spaced number between 1 and 50\n-------------------------------------------')
print(np.linspace(1,5,50))

#1--starting point, 5----end point, 50-----total numbers to be generated

linearly spaced number between 1 and 50
-------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [ ]:
np.linspace(1,5,10,endpoint=True)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,10,endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [ ]:
np.linspace(2.0,3.0,num=10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [ ]:
np.linspace(2.0,3.0,num=10,endpoint=False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

**Logspace**

In [ ]:
np.logspace(2.0,3.0,num=5,base=10)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [ ]:
np.logspace(2.0,3.0,num=5,base=3)

array([ 9.        , 11.84466612, 15.58845727, 20.51556351, 27.        ])

In [ ]:
np.logspace(2.0,3.0,num=5,endpoint=False)

array([100.        , 158.48931925, 251.18864315, 398.10717055,
       630.95734448])

**Matrix Creation**

In [ ]:
print("Vector of zeros\n----------------------\n")
print(np.zeros(5))

Vector of zeros
----------------------

[0. 0. 0. 0. 0.]


In [ ]:
print("Matrix of zeros\n------------------------")
print(np.zeros((3,4)))    #Notice tuples

Matrix of zeros
------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print("Vector of ones\n----------------")
print(np.ones(5))

Vector of ones
----------------
[1. 1. 1. 1. 1.]


In [ ]:
print("Matrix of zeros\n------------------")
print(np.zeros((3,4,2)))

3D array of 4x2

Matrix of zeros
------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
print("Matrix of ones\n-----------------")
print(np.ones((5,2,8)))

Matrix of ones
-----------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
print("Matrix of 5's\n-------------------")
print(5+np.ones((3,4)))

Matrix of 5's
-------------------
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [ ]:
np.ones((3,4))+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
np.ones((3,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [ ]:
print("Empty Matrix\n------------------------\n",np.empty((3,5)))

#np.empty will pick up any random number

Empty Matrix
------------------------
 [[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [ ]:
mat1=np.eye(5)
print("Identity matrix of dimension",mat1.shape)
print(mat1)

Identity matrix of dimension (5, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Assignment**

In [ ]:
print(np.zeros((2,4,8))+5*2)

[[[10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]]

 [[10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]]]


In [ ]:
print(np.linspace(4,8,80))

[4.         4.05063291 4.10126582 4.15189873 4.20253165 4.25316456
 4.30379747 4.35443038 4.40506329 4.4556962  4.50632911 4.55696203
 4.60759494 4.65822785 4.70886076 4.75949367 4.81012658 4.86075949
 4.91139241 4.96202532 5.01265823 5.06329114 5.11392405 5.16455696
 5.21518987 5.26582278 5.3164557  5.36708861 5.41772152 5.46835443
 5.51898734 5.56962025 5.62025316 5.67088608 5.72151899 5.7721519
 5.82278481 5.87341772 5.92405063 5.97468354 6.02531646 6.07594937
 6.12658228 6.17721519 6.2278481  6.27848101 6.32911392 6.37974684
 6.43037975 6.48101266 6.53164557 6.58227848 6.63291139 6.6835443
 6.73417722 6.78481013 6.83544304 6.88607595 6.93670886 6.98734177
 7.03797468 7.08860759 7.13924051 7.18987342 7.24050633 7.29113924
 7.34177215 7.39240506 7.44303797 7.49367089 7.5443038  7.59493671
 7.64556962 7.69620253 7.74683544 7.79746835 7.84810127 7.89873418
 7.94936709 8.        ]


In [ ]:
list=[1,2,3,4,5]
np.mat(list)

matrix([[1, 2, 3, 4, 5]])

In [ ]:
b=np.ones((4,5,2))
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
print(b.ndim)

3


In [ ]:
print(b.shape)

(4, 5, 2)


In [ ]:
print(b.dtype)

float64


In [ ]:
x1=np.ones((3,3,3))
x2=np.ones((3,3,3))+5
x1+x2

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [ ]:
a=9
np.array(a).ndim
np.array([4,5,6]).ndim

1

**reshape()**

In [ ]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.arange(16).reshape((4,4,1))

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]])

In [ ]:
np.arange(16).reshape((1,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x=np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x)

array([ 0,  5, 10, 15])

In [ ]:
np.diag(x,k=0)

array([ 0,  5, 10, 15])

In [ ]:
y=np.arange(16).reshape((-1,8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
np.diag(y)

#diagonal matrix of the 1st squared array

array([0, 9])

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [ ]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [ ]:
np.diag(x,k=-4)

array([], dtype=int64)

In [ ]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
#create a 2D array with the flattened input as diagonal

np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diagflat([[1,2],[3,4]],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [ ]:
np.diagflat([[1,2],[3,4]],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere

np.tri(4,4,1,dtype=float)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.tri(4,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [ ]:

np.tri(4,4,0,dtype=float)

#k=0

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [ ]:

a=np.tri(4,4,2,dtype=float)
a

#k=2


array([[1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a[0]

array([1., 1., 1., 0.])

In [ ]:
for i in a:
  print(i)

[1. 1. 1. 0.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]


In [ ]:
for i in a:
  for j in i:
    print(j)

1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [ ]:
#return a lower triangle of an array


np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#return upper triangle of an array

np.triu([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [ ]:

np.triu([[1,2,3],[4,5,6],[7,8,9]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [ ]:

np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

**Random Number Generation**

In [ ]:
print('Random number Generation (from Uniform Distribution)')
print(np.random.rand(2,3)) #2 by 3 matrix with random numbers ranging between 0 to 1. No tuple necessary.

#uniform distribution: numbers ranging in between 0 to 1.

Random number Generation (from Uniform Distribution)
[[0.02316527 0.989543   0.31711982]
 [0.10937497 0.36002954 0.63066302]]


In [ ]:
print('Random number Generation (from Uniform Distribution)')
print(np.random.rand(2,3,8))

Random number Generation (from Uniform Distribution)
[[[0.48001756 0.58949767 0.62716514 0.65461442 0.16415232 0.00106478
   0.0107007  0.09133153]
  [0.86508251 0.14413736 0.37050847 0.73654619 0.22541563 0.38116845
   0.44104752 0.48474222]
  [0.41059956 0.01517798 0.93909845 0.55945384 0.54954574 0.50494474
   0.71175315 0.28167713]]

 [[0.99494203 0.76828895 0.69267339 0.62806457 0.24188873 0.21489013
   0.79109672 0.80464172]
  [0.79431901 0.15554729 0.46886734 0.73807949 0.27071451 0.43271573
   0.19009937 0.8649948 ]
  [0.45589974 0.85323253 0.69126596 0.8877716  0.38714111 0.92695298
   0.38712318 0.05119019]]]


In [ ]:
print('Numbers from Normal Distribution with mean 0 and standard deviation is 1 i.e. standard normal')
print(np.random.randn(4,3))

Numbers from Normal Distribution with mean 0 and standard deviation is 1 i.e. standard normal
[[ 0.29137389  0.39208375  0.52126551]
 [-1.53409127  1.14477487 -0.4584743 ]
 [ 1.27130021 -0.33429532 -0.60989493]
 [-0.42879581 -0.51040574 -0.51256465]]


In [ ]:
print('Numbers from Normal Distribution with mean 0 and standard deviation is 1 i.e. standard normal')
print(np.random.randn(4,3,5))

#rand : It will give output based on uniform distribution
#randn : It will give output based on standard normal distribution

Numbers from Normal Distribution with mean 0 and standard deviation is 1 i.e. standard normal
[[[ 0.54036983  0.30219158 -0.22326521 -0.97296347 -0.5069206 ]
  [ 0.67857063  0.5275085   1.79943292  0.97062297  0.92851216]
  [ 0.17339856 -0.51019708 -1.25728376  0.41806948 -1.76796937]]

 [[-1.80502309 -0.05134099 -1.22353375  0.79105998 -1.58571625]
  [-2.11584475 -0.22825207 -2.50495375 -1.12616685  0.81721113]
  [ 0.46714552 -0.32670322  2.28795187 -1.22912909  0.91993384]]

 [[ 0.76806582 -0.53634495 -0.89919792  1.75738795 -0.74336967]
  [ 0.59473445 -1.06746662 -0.77026813 -0.76213373 -0.23146997]
  [ 1.83592799 -0.23282825 -0.02290159 -0.08011643 -0.4014776 ]]

 [[-0.37104419  0.93980091  0.8656171   1.73882269  0.69733982]
  [-1.218177    0.03768255  0.62982687  0.04060585 -1.4388184 ]
  [ 0.84251592 -0.2879922   0.14575282  2.69158252  0.08109791]]]


In [ ]:
print('Random integer vector:',np.random.randint(1,10)) #randint(low,high,# of samples to be drawn)
print('\nRandom Integer Matrix\n')
np.random.randint(1,10)

Random integer vector: 4

Random Integer Matrix



9

In [ ]:
print(np.random.randint(1,100,(4,4))) #randint(low,high, # od samples to be drawn in a tuple ro form a matrix)
print('\n 20 samples drawn from a dice throw:',np.random.randint(1,7,20))


[[23 73 15 99]
 [21 29 68 57]
 [98 83  7 80]
 [49 15 60 50]]

 20 samples drawn from a dice throw: [6 6 6 2 3 2 5 1 5 4 2 2 5 3 4 4 1 4 4 5]


**Reshaping**

In [1]:
from numpy.random import randint as ri
a=ri(1,100,30)
a

array([85,  7, 27, 12, 58, 26, 73, 53, 32, 34,  3,  4, 25, 98, 84, 20,  3,
       98,  5, 92, 93, 37, 18, 21, 84, 44, 78, 98, 81, 46])

In [ ]:
b=a.reshape(2,3,5)
b

array([[[74,  6,  6, 11, 60],
        [13, 78, 33, 77, 13],
        [40, 13, 20, 15, 52]],

       [[ 1, 44, 41, 43,  7],
        [69, 49, 74, 42, 33],
        [ 2, 36, 18, 55, 28]]])

In [ ]:
c=b.reshape(6,-19878)
c

array([[74,  6,  6, 11, 60],
       [13, 78, 33, 77, 13],
       [40, 13, 20, 15, 52],
       [ 1, 44, 41, 43,  7],
       [69, 49, 74, 42, 33],
       [ 2, 36, 18, 55, 28]])

In [ ]:
print('Shape of a:',a.shape)
print('Shape of b:',b.shape)
print('Shape of c:',c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
print("\na looks like\n","-"*20,"\n",a,"\n","-"*20)
print("\nb looks like\n","-"*20,"\n",b,"\n","-"*20)
print("\nc looks like\n","-"*20,"\n",c,"\n","-"*20)


a looks like
 -------------------- 
 [74  6  6 11 60 13 78 33 77 13 40 13 20 15 52  1 44 41 43  7 69 49 74 42
 33  2 36 18 55 28] 
 --------------------

b looks like
 -------------------- 
 [[[74  6  6 11 60]
  [13 78 33 77 13]
  [40 13 20 15 52]]

 [[ 1 44 41 43  7]
  [69 49 74 42 33]
  [ 2 36 18 55 28]]] 
 --------------------

c looks like
 -------------------- 
 [[74  6  6 11 60]
 [13 78 33 77 13]
 [40 13 20 15 52]
 [ 1 44 41 43  7]
 [69 49 74 42 33]
 [ 2 36 18 55 28]] 
 --------------------


In [ ]:
A=ri(1,100,10)
print('\nVector of random integers\n',"-"*50,'\n',A)
print('\nHere is the sorted vector\n',"-"*50,'\n',np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [39 37 86 11 67 99  4 11 26 30]

Here is the sorted vector
 -------------------------------------------------- 
 [ 4 11 11 26 30 37 39 67 86 99]


In [ ]:
#Matrix of random integers

M=ri(1,100,25).reshape(5,5)
M

array([[ 1, 72, 14, 74,  9],
       [78, 87, 87, 37, 41],
       [97,  6,  9, 87,  8],
       [39, 20, 87, 63, 98],
       [84, 82, 33,  6, 86]])

In [ ]:
print('\nHere is the sorted matrix along each row\n',"-"*50,"\n",np.sort(M,kind='mergesort',axis=0))
print('\nHere is the sorted matrix along each column\n',"-"*50,"\n",np.sort(M,kind='mergesort',axis=1))

#axis 0 and 1 signifies the movement of the data.


Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 1  6  9  6  8]
 [39 20 14 37  9]
 [78 72 33 63 41]
 [84 82 87 74 86]
 [97 87 87 87 98]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 1  9 14 72 74]
 [37 41 78 87 87]
 [ 6  8  9 87 97]
 [20 39 63 87 98]
 [ 6 33 82 84 86]]


In [ ]:
print("Max of a:",M.max())
print("Max of b:",b.max())
b

Max of a: 98
Max of b: 78


array([[[74,  6,  6, 11, 60],
        [13, 78, 33, 77, 13],
        [40, 13, 20, 15, 52]],

       [[ 1, 44, 41, 43,  7],
        [69, 49, 74, 42, 33],
        [ 2, 36, 18, 55, 28]]])

In [ ]:
M

array([[ 1, 72, 14, 74,  9],
       [78, 87, 87, 37, 41],
       [97,  6,  9, 87,  8],
       [39, 20, 87, 63, 98],
       [84, 82, 33,  6, 86]])

In [ ]:
print("Max of a location:",M.argmax(axis=1))
print("Max of b location:",b.argmax(axis=1))
print("Max of c location:",c.argmax(axis=1))

Max of a location: [3 1 0 4 4]
Max of b location: [[0 1 1 1 0]
 [1 1 1 2 1]]
Max of c location: [0 1 4 1 2 3]


In [ ]:
print("Max of a location:",M.argmax())
print("Max of b location:",b.argmax())
print("Max of c location:",c.argmax())

Max of a location: 19
Max of b location: 6
Max of c location: 6


**Indexing ans Slicing**

In [ ]:
arr=np.arange(0,11)
print("Array",arr)

Array [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Element of 7th Index is:",arr[7])

Element of 7th Index is: 7


In [ ]:
print("Elements from 3rd to 5th Index are:",arr[3:6:2])

Elements from 3rd to 5th Index are: [3 5]


In [ ]:
print("Elements upto 4th index:",arr[:4])

Elements upto 4th index: [0 1 2 3]


In [ ]:
print("Elements from last backwards are:",arr[-1:7:-1])

Elements from last backwards are: [10  9  8]


In [2]:
arr=np.arange(0,21,2)
print('New array',arr)

New array [ 0  2  4  6  8 10 12 14 16 18 20]


In [6]:
print('Elements at 2nd, 4th and 9th index are:',arr[[2,4,9]]) #pass a list as an index to subset. 

Elements at 2nd, 4th and 9th index are: [ 4  8 18]


In [6]:
import numpy as np
mat=np.array(ri(10,100,45)).reshape(3,5,3)
print("Matrix of random 2 digit numbers\n------------------------\n",mat)

Matrix of random 2 digit numbers
------------------------
 [[[11 84 70]
  [26 85 69]
  [84 23 24]
  [51 34 40]
  [89 99 42]]

 [[53 78 19]
  [44 45 39]
  [48 20 83]
  [24 32 84]
  [93 48 68]]

 [[50 61 83]
  [39 63 37]
  [93 15 55]
  [87 31 30]
  [99 89 70]]]


In [3]:
mat[1:4,3:5]

array([[60, 90],
       [62, 54]])

In [8]:
mat[1,1] 

array([44, 45, 39])

In [9]:
mat[1][1]

array([44, 45, 39])

In [10]:
mat[1][1][0]

44

In [13]:
mat[0][:,1]

array([84, 85, 23, 34, 99])

In [17]:
mat[0:3,0:2]

array([[[11, 84, 70],
        [26, 85, 69]],

       [[53, 78, 19],
        [44, 45, 39]],

       [[50, 61, 83],
        [39, 63, 37]]])

In [18]:
mat[0:3,[0,1]]

array([[[11, 84, 70],
        [26, 85, 69]],

       [[53, 78, 19],
        [44, 45, 39]],

       [[50, 61, 83],
        [39, 63, 37]]])

In [21]:
for i in range(3):
  print(mat[i][0:2,:])

[[11 84 70]
 [26 85 69]]
[[53 78 19]
 [44 45 39]]
[[50 61 83]
 [39 63 37]]


**Subsetting**

In [23]:
mat=np.array(ri(10,100,15).reshape(3,5))
print('Matrix of random 2 digit numbers\n---------------------\n',mat)

Matrix of random 2 digit numbers
---------------------
 [[74 57 90 35 15]
 [33 84 69 14 81]
 [59 58 34 50 82]]


In [24]:
mat>50

array([[ True,  True,  True, False, False],
       [False,  True,  True, False,  True],
       [ True,  True, False, False,  True]])

In [26]:
print('Elements greater than 50\n---------------------------\n',mat[mat>50])

Elements greater than 50
---------------------------
 [74 57 90 84 69 81 59 58 82]


**Universal Functions**



In [28]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print('1st Matrix of single digit number:\n------------------------------\n',mat1)
print('2nd Matrix of single digit number:\n------------------------------\n',mat2)

1st Matrix of single digit number:
------------------------------
 [[2 7 3]
 [3 2 3]
 [7 9 9]]
2nd Matrix of single digit number:
------------------------------
 [[1 4 7]
 [3 1 9]
 [4 5 3]]


In [29]:
mat1*mat2

array([[ 2, 28, 21],
       [ 9,  2, 27],
       [28, 45, 27]])

In [30]:
mat1@mat2       

array([[ 35,  30,  86],
       [ 21,  29,  48],
       [ 70,  82, 157]])

In [32]:
print('Addition\n-------------\n',mat1+mat2)

Addition
-------------
 [[ 3 11 10]
 [ 6  3 12]
 [11 14 12]]


In [33]:
print('Multiplication\n-------------\n',mat1*mat2)

Multiplication
-------------
 [[ 2 28 21]
 [ 9  2 27]
 [28 45 27]]


In [34]:
#exception in python

2/0

ZeroDivisionError: ignored

In [38]:
print('Division\n-------------------\n',mat1/0)

Division
-------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [40]:
print('Addition of a scaler(100)\n-------------------------\n',100+mat1)

Addition of a scaler(100)
-------------------------
 [[102 107 103]
 [103 102 103]
 [107 109 109]]


In [41]:
print('Exponentiation,matrix cubed here\n-----------------------\n',mat1**3)
print('Exponentiation,square root using power function\n-----------------------\n',pow(mat1,3))

Exponentiation,matrix cubed here
-----------------------
 [[  8 343  27]
 [ 27   8  27]
 [343 729 729]]
Exponentiation,square root using power function
-----------------------
 [[  8 343  27]
 [ 27   8  27]
 [343 729 729]]


**Broadcast**

In [45]:
start=np.zeros((4,4))
start=start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [48]:
#row wise broadcasting operation
add_rows=np.array([1,0,2,5])
print(add_rows)

[1 0 2 5]


In [51]:
y=start+add_rows  # add to each row of start using broadcasting 
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [55]:
#column wise broadcasting

add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T    #Transpose operation is must in column wise broadcasting 
add_cols



array([[0],
       [1],
       [2],
       [3]])

In [57]:
np.array([[0,1,2,3]])

array([[0, 1, 2, 3]])

In [58]:
np.array([[0,1,2,3]]).T

array([[0],
       [1],
       [2],
       [3]])

In [59]:
y1=start+add_cols
print(y1)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [61]:
#this will just broadcast in both directions

add_scaler=np.array([100])
print(start+y)

[[201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]]


**Array Math**

In [63]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print('1st matrix of random single digit\n---------------------------------\n',mat1)
print('2nd matrix of random single digit\n---------------------------------\n',mat2)

1st matrix of random single digit
---------------------------------
 [[2 3 9]
 [4 8 9]
 [8 2 9]]
2nd matrix of random single digit
---------------------------------
 [[3 5 4]
 [3 1 2]
 [2 1 9]]


In [66]:
print('Square root of 1st matrix using np\n---------------------------------------\n',np.sqrt(mat1))

Square root of 1st matrix using np
---------------------------------------
 [[1.41421356 1.73205081 3.        ]
 [2.         2.82842712 3.        ]
 [2.82842712 1.41421356 3.        ]]


In [68]:
print('Exponential power of 1st matrix using np\n----------------------------------------------\n',np.exp(mat1))

Exponential power of 1st matrix using np
----------------------------------------------
 [[7.38905610e+00 2.00855369e+01 8.10308393e+03]
 [5.45981500e+01 2.98095799e+03 8.10308393e+03]
 [2.98095799e+03 7.38905610e+00 8.10308393e+03]]


In [70]:
print('Exponential power of 1st matrix using np\n','-'*50,'\n',np.exp(mat1))

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[7.38905610e+00 2.00855369e+01 8.10308393e+03]
 [5.45981500e+01 2.98095799e+03 8.10308393e+03]
 [2.98095799e+03 7.38905610e+00 8.10308393e+03]]


In [75]:
print('10-base logarithm on 1st matrix using np\n','-'*50,'\n',np.log10(mat1))

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.30103    0.47712125 0.95424251]
 [0.60205999 0.90308999 0.95424251]
 [0.90308999 0.30103    0.95424251]]


In [76]:
print('10-base logarithm on 1st matrix using np\n','-'*50,'\n',np.log10(mat2))

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.47712125 0.69897    0.60205999]
 [0.47712125 0.         0.30103   ]
 [0.30103    0.         0.95424251]]


In [77]:
print('Modulo reminder using np\n','-'*50,'\n',np.fmod(mat1,mat2))

Modulo reminder using np
 -------------------------------------------------- 
 [[2 3 1]
 [1 0 1]
 [0 0 0]]


In [78]:
mat1%mat2

array([[2, 3, 1],
       [1, 0, 1],
       [0, 0, 0]])

In [79]:
print('Combination of functions showing exponential decay of a sine wave\n','-'*70)

Combination of functions showing exponential decay of a sine wave
 ----------------------------------------------------------------------


In [81]:
A=np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])